# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
sudo: false
language: rust
compiler: gcc

notifications:
  email: false

rust:
  - stable
  - nightly

os:
  - linux

branches:
  only:
    - master
    - travis

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - libgtk-3-dev
    - libgtk-3-0
    - libstdc++-6-pic


before_install:
  - set -e
  - rustup self update
  - curl -so "$TRAVIS_BUILD_DIR/libsciter-gtk.so" https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.gtk/x64/libsciter-gtk.so

install:
  - source ~/.cargo/env || true

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi

  - export PATH="$PATH:$TRAVIS_BUILD_DIR"
  - export LIBRARY_PATH="$LIBRARY_PATH:$TRAVIS_BUILD_DIR"
  - export RUST_BACKTRACE=full
  - export RUSTFLAGS='-C link-arg=-Wl,--unresolved-symbols=ignore-in-shared-libs'

  - #ls /usr/lib/x86_64-linux-gnu/libstdc++*
  - #strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
  - gcc --version

script:
  - cargo run --example first
  - cargo clean
  - cargo build --all
  - cargo build --all --release
  - cargo build --examples --release
  - #cargo test --all
  - #cargo test --all --release

after_script: set +e
